CREATE TABLE [dbo].[Sale]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[CashierID] NVARCHAR(128) FOREIGN KEY REFERENCES UserTable([UserId]),
	SaleDate DATETIME2 NOT NULL,
	[SubTotal] MONEY NOT NULL,
	[Tax] MONEY NOT NULL,
	[Total] MONEY NOT NULL 
)
